//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contas_Pagar
    {
        public long Id { get; set; }
        public Nullable<long> Id_fornecedor { get; set; }
        public string Documento { get; set; }
        public string valor { get; set; }
        public Nullable<System.DateTime> vencimento { get; set; }
        public Nullable<long> categoria { get; set; }
        public Nullable<System.DateTime> previsao { get; set; }
        public string pago { get; set; }
    }
}
