//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item_Livro_Caixa
    {
        public long Id { get; set; }
        public Nullable<long> Id_livro { get; set; }
        public string tipo { get; set; }
        public string descricao { get; set; }
        public string documento { get; set; }
        public Nullable<decimal> valor { get; set; }
    
        public virtual Livro_Caixa livro_caixa { get; set; }
    }
}
