//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemPedido_InfoAdic
    {
        public long Id { get; set; }
        public long Id_itempedido { get; set; }
        public Nullable<decimal> peso_liquido { get; set; }
        public Nullable<decimal> peso_bruto { get; set; }
        public string numero_pedido_compra { get; set; }
        public Nullable<int> item_pedido_compra { get; set; }
        public string dados_adicionais_item { get; set; }
        public string nao_movimentar_estoque { get; set; }
        public string nao_gerar_financeiro { get; set; }
        public Nullable<System.DateTime> inclusao { get; set; }
        public string usuario_inclusao { get; set; }
        public Nullable<System.DateTime> alteracao { get; set; }
        public string usuario_alteracao { get; set; }
    
        public virtual ItemPedido itempedido { get; set; }
    }
}
