//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produto_Ibpt
    {
        public long Id { get; set; }
        public long Id_produto { get; set; }
        public Nullable<decimal> aliqFederal { get; set; }
        public Nullable<decimal> aliqEstadual { get; set; }
        public Nullable<decimal> aliqMunicipal { get; set; }
        public string fonte { get; set; }
        public string chave { get; set; }
        public Nullable<System.DateTime> inclusao { get; set; }
        public string usuario_inclusao { get; set; }
        public Nullable<System.DateTime> alteracao { get; set; }
        public string usuario_alteracao { get; set; }
    
        public virtual Produto produto { get; set; }
    }
}
