//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Categoria
    {
        public long Id { get; set; }
        public string codigo { get; set; }
        public string descricao { get; set; }
        public string descricao_padrao { get; set; }
        public string conta_inativa { get; set; }
        public string definida_pelo_usuario { get; set; }
        public Nullable<int> id_conta_contabil { get; set; }
        public string tag_conta_contabil { get; set; }
        public string conta_despesa { get; set; }
        public string nao_exibir { get; set; }
        public string natureza { get; set; }
        public string conta_receita { get; set; }
        public string totalizadora { get; set; }
        public string transferencia { get; set; }
        public Nullable<int> controle { get; set; }
    }
}
