//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Funcao_Perfil
    {
        public Funcao_Perfil()
        {
        }
        public Funcao_Perfil(bool InitPropertys)
        {
            consultar = "N";
            editar = "N";
            excluir = "N";
            salvar = "N";
            imprimir = "N";
        }

        public long Id { get; set; }
        public long Id_perfil { get; set; }
        public int codigo_funcao { get; set; }
        public string cancelar { get; set; }
        public string consultar { get; set; }
        public string editar { get; set; }
        public string excluir { get; set; }
        public string salvar { get; set; }
        public string imprimir { get; set; }
        public Nullable<System.DateTime> inclusao { get; set; }
        public string usuario_inclusao { get; set; }
        public Nullable<System.DateTime> alteracao { get; set; }
        public string usuario_alteracao { get; set; }
    
        public virtual Funcao funcao { get; set; }
        public virtual Perfil perfil { get; set; }
    }
}
