//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemPedido_Produto
    {
        public long Id { get; set; }
        public long Id_itempedido { get; set; }
        public long Id_produto { get; set; }
        public Nullable<int> ordem { get; set; }
        public string codigo_produto_integracao { get; set; }
        public string codigo { get; set; }
        public string descricao { get; set; }
        public string cfop { get; set; }
        public string ncm { get; set; }
        public string ean { get; set; }
        public string unidade { get; set; }
        public Nullable<decimal> quantidade { get; set; }
        public Nullable<decimal> valor_unitario { get; set; }
        public Nullable<decimal> valor_mercadoria { get; set; }
        public string tipo_desconto { get; set; }
        public Nullable<decimal> percentual_desconto { get; set; }
        public Nullable<decimal> valor_desconto { get; set; }
        public Nullable<decimal> valor_deducao { get; set; }
        public Nullable<decimal> valor_total { get; set; }
        public Nullable<System.DateTime> inclusao { get; set; }
        public string usuario_inclusao { get; set; }
        public Nullable<System.DateTime> alteracao { get; set; }
        public string usuario_alteracao { get; set; }
        public Nullable<int> codigo_produto { get; set; }
    
        public virtual ItemPedido itempedido { get; set; }
        public virtual Produto produto { get; set; }
    }
}
