//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedido_Otica
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pedido_Otica()
        {
            this.itempedido_otica = new HashSet<ItemPedido_Otica>();
            this.pedido_armacao = new HashSet<Pedido_Armacao>();
            this.pedido_lente = new HashSet<Pedido_Lente>();
            this.pedido_otica_infoadic = new HashSet<Pedido_Otica_InfoAdic>();
            this.pedido_otica_parcelas = new HashSet<Pedido_Otica_Parcelas>();
        }
    
        public long Id { get; set; }
        public Nullable<long> Id_cliente { get; set; }
        public Nullable<long> codigo { get; set; }
        public string codigo_cliente { get; set; }
        public Nullable<long> Id_pedido { get; set; }
        public string codigo_pedido { get; set; }
        public Nullable<System.DateTime> data_emissao { get; set; }
        public Nullable<System.DateTime> data_fechamento { get; set; }
        public Nullable<long> condicao_pagamento { get; set; }
        public string numero_pedido_cliente { get; set; }
        public Nullable<System.DateTime> date_previsao_entrega { get; set; }
        public Nullable<System.TimeSpan> hora_previsao_entrega { get; set; }
        public Nullable<long> id_motivo_entrega { get; set; }
        public Nullable<long> Id_transportadora { get; set; }
        public string od_gl_esf { get; set; }
        public string od_gl_cil { get; set; }
        public Nullable<int> od_eixo { get; set; }
        public string od_adicao { get; set; }
        public string od_gp_esf { get; set; }
        public string od_gp_cil { get; set; }
        public string oe_gl_esf { get; set; }
        public string oe_gl_cil { get; set; }
        public Nullable<int> oe_eixo { get; set; }
        public string oe_adicao { get; set; }
        public string oe_gp_esf { get; set; }
        public string oe_gp_cil { get; set; }
        public string od_dnp_longe { get; set; }
        public string od_dnp_perto { get; set; }
        public string od_alt { get; set; }
        public string od_dech { get; set; }
        public string od_prisma_valor { get; set; }
        public Nullable<int> od_prisma_eixo { get; set; }
        public string oe_dnp_longe { get; set; }
        public string oe_dnp_perto { get; set; }
        public string oe_alt { get; set; }
        public string oe_dech { get; set; }
        public string oe_prisma_valor { get; set; }
        public Nullable<int> oe_prisma_eixo { get; set; }
        public string base_calculada { get; set; }
        public string numero_caixa { get; set; }
        public Nullable<int> status { get; set; }
        public string agrupado { get; set; }
        public Nullable<long> Id_vendedor { get; set; }
        public Nullable<int> Id_caixa { get; set; }
        public string cancelado { get; set; }
        public Nullable<System.DateTime> data_cancelamento { get; set; }
        public string motivo_cancelamento { get; set; }
        public Nullable<System.DateTime> inclusao { get; set; }
        public string usuario_inclusao { get; set; }
        public Nullable<System.DateTime> alteracao { get; set; }
        public string usuario_alteracao { get; set; }
    
        public virtual Cliente cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemPedido_Otica> itempedido_otica { get; set; }
        public virtual Motivo_Entrega motivo_entrega { get; set; }
        public virtual Pedido pedido { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pedido_Armacao> pedido_armacao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pedido_Lente> pedido_lente { get; set; }
        public virtual Parcela parcela { get; set; }
        public virtual Vendedor vendedor { get; set; }
        public virtual Cliente transportadora { get; set; }
        public virtual Caixa caixa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pedido_Otica_InfoAdic> pedido_otica_infoadic { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pedido_Otica_Parcelas> pedido_otica_parcelas { get; set; }
    }
}
