//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedido_Frete
    {
        public decimal Id { get; set; }
        public long Id_pedido { get; set; }
        public Nullable<int> codigo_transportadora { get; set; }
        public string codigo_transportadora_integracao { get; set; }
        public string modalidade { get; set; }
        public string placa { get; set; }
        public string placa_estado { get; set; }
        public Nullable<int> quantidade_volumes { get; set; }
        public string especie_volumes { get; set; }
        public string marca_volumes { get; set; }
        public string numeracao_volumes { get; set; }
        public Nullable<decimal> peso_liquido { get; set; }
        public Nullable<decimal> peso_bruto { get; set; }
        public Nullable<decimal> valor_frete { get; set; }
        public Nullable<decimal> valor_seguro { get; set; }
        public string registro_transportador { get; set; }
        public Nullable<System.DateTime> inclusao { get; set; }
        public string usuario_inclusao { get; set; }
        public Nullable<System.DateTime> alteracao { get; set; }
        public string usuario_alteracao { get; set; }
    
        public virtual Pedido pedido { get; set; }
    }
}
