//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedido_InfoAdic
    {
        public long Id { get; set; }
        public long Id_Pedido { get; set; }
        public string codigo_categoria { get; set; }
        public int codigo_conta_corrente { get; set; }
        public string numero_pedido_cliente { get; set; }
        public string numero_contrato { get; set; }
        public string contato { get; set; }
        public string dados_adicionais_nf { get; set; }
        public string consumidor_final { get; set; }
        public string utilizar_emails { get; set; }
        public string enviar_email { get; set; }
        public Nullable<int> codVend { get; set; }
        public Nullable<int> codProj { get; set; }
        public Nullable<System.DateTime> inclusao { get; set; }
        public string usuario_inclusao { get; set; }
        public Nullable<System.DateTime> alteracao { get; set; }
        public string usuario_alteracao { get; set; }
        public long Id_conta_corrente { get; set; }
    
        public virtual Pedido pedido { get; set; }
        public virtual Conta_Corrente conta_corrente { get; set; }
    }
}
